version: 0.2

phases:
  build:
    commands:
      - echo Entered the build phase...
  post_build:
    commands:
      - echo Build completed successfully
artifacts:
  files:
    - target/st-schools.jar
  discard-paths: yes