openapi: 3.0.0
info:
  version: "1.0.0"
  title: "st-schools"
servers:
  - url: "http://localhost:8080"

tags:
  - name: "AdminController"
  - name: "AuthenticationController"
  - name: "RegistrationController"
  - name: "UserController"
